# schema_search_path should be datacommon,public

default: &default
  adapter:  postgresql
  database: <%= ENV.fetch('DB_NAME') { 'housingma_dev' } %>
  username: <%= ENV.fetch('DB_USERNAME') { nil } %>
  password: <%= ENV.fetch('DB_PASSWORD') { nil } %>
  host:     <%= ENV.fetch('DB_PORT_5432_TCP_ADDR') { 'localhost' } %>
  port:     <%= ENV.fetch('DB_PORT_5432_TCP_PORT') { '5432' }      %>
  schema_search_path: <%= ENV.fetch('DB_SCHEMA_SEARCH_PATH') { "housingma,public" } %>
  timeout:  5000
  pool:     5


development: &development
  <<: *default


production: &production
  <<: *default


commondata: &commondata
  url: <%= ENV.fetch('COMMON_DB_URL') %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  schema_search_path: <%= ENV.fetch('COMMON_DB_SCHEMA_SEARCH_PATH') { 'public,postgis' } %>


geographic: &geographic
  url: <%= ENV.fetch('GEOGRAPHIC_DB_URL') %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  schema_search_path: <%= ENV.fetch('GEO_DB_SCHEMA_SEARCH_PATH') { 'spatial,public,postgis' } %>

housing_data:
  url: <%= ENV.fetch('HOUSING_DATA_DB_URL') %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test: &test
  <<: *default
  database: housingma_test
  host:     localhost
